-- Table: public.pets

DROP TABLE IF EXISTS public.pets;

CREATE TABLE IF NOT EXISTS public.pets
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    bio character varying COLLATE pg_catalog."default" NOT NULL,
    image_url text COLLATE pg_catalog."default",
    CONSTRAINT pets_pkey PRIMARY KEY (id),
    CONSTRAINT pets_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pets
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.pets
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.pets TO anon;

GRANT ALL ON TABLE public.pets TO authenticated;

GRANT ALL ON TABLE public.pets TO postgres;

GRANT ALL ON TABLE public.pets TO service_role;

GRANT ALL ON TABLE public.pets TO supabase_admin;

-- POLICY: Enable delete for authenticated users on user_id

DROP POLICY IF EXISTS "Enable delete for authenticated users on user_id" ON public.pets;

CREATE POLICY "Enable delete for authenticated users on user_id"
    ON public.pets
    AS PERMISSIVE
    FOR DELETE
    TO authenticated
    USING ((user_id = auth.uid()));

-- POLICY: Enable insert for authenticated users on user_id

DROP POLICY IF EXISTS "Enable insert for authenticated users on user_id" ON public.pets;

CREATE POLICY "Enable insert for authenticated users on user_id"
    ON public.pets
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((user_id = auth.uid()));

-- POLICY: Enable select for authenticated users

DROP POLICY IF EXISTS "Enable select for authenticated users" ON public.pets;

CREATE POLICY "Enable select for authenticated users"
    ON public.pets
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING (true);

-- POLICY: Enable update for authenticated users on user_id

DROP POLICY IF EXISTS "Enable update for authenticated users on user_id" ON public.pets;

CREATE POLICY "Enable update for authenticated users on user_id"
    ON public.pets
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated
    USING ((user_id = auth.uid()))
    WITH CHECK ((user_id = auth.uid()));

INSERT  into storage.buckets (id, name, public) 
VALUES  ('images', 'images', true)
ON CONFLICT DO NOTHING;

CREATE POLICY "Enable access for authenticated users only"
    ON storage.objects
    AS PERMISSIVE
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);